/**
 * `MockAdapter` — a deterministic, network-free adapter.
 *
 * Used by the unit/contract suites and by the headless e2e driver, which commits the bytes
 * `fetchOutputs` produces as real project assets. That constrains the implementation:
 *   * `fetchOutputs` returns genuinely valid PNG and WAV bytes (see `bytes.ts`), not `"x"`;
 *   * every id, byte and cost is derived from a hash of the request, so two runs of the same
 *     request are byte-identical and e2e hashes are stable;
 *   * failure injection is explicit (`failFirstN`, `failWith`) and never leaks into other
 *     calls.
 *
 * Failure scenarios used by the contract suite can be injected three ways: `failWith` for
 * the submit path, `malformedResponses` for the catalog path, and `requireCredentials` for
 * the credential path.
 */
import {
  CredentialError,
  ProviderError,
  classifyHttpStatus,
  nextBackoffDelay,
  type CreativeLabError,
  type Spend,
} from "@creativelab/core";
import { billableUnits, costFromPricing } from "../cost.js";
import type { ProviderAdapter, ProviderContext } from "../adapter.js";
import { credentialErrorFromResponse, normalizeProviderError, submissionError } from "../errors.js";
import { capabilitiesFrom, type ModelCapabilities, type ModelDescriptor } from "../capabilities.js";
import type {
  GenerationRequest,
  Issue,
  JobStatusResult,
  RemoteOutput,
  SubmitResult,
  ValidationResult,
} from "../requests.js";
import { validateRequest } from "../validate.js";
import { assertOutputsFresh } from "../remote.js";
import { encodePng, encodeText, encodeVideoBlob, encodeWav } from "./bytes.js";

export interface MockAdapterOptions {
  /** Artificial delay applied to every call. Defaults to 0 so tests stay fast. */
  readonly latencyMs?: number;
  /** Fail the first N submissions with `failWith`, then succeed. */
  readonly failFirstN?: number;
  /** How the injected failure looks. Defaults to a retryable 500. */
  readonly failWith?: {
    status?: number;
    message?: string;
    category?: CreativeLabError["category"];
    retryable?: boolean;
    uncertain?: boolean;
  };
  /** Seed the generated bytes; two different seeds produce different output. */
  readonly seedOutputs?: number;
  /** Injectable clock. */
  readonly now?: () => Date;
  /** Retries after the first failed attempt, mirroring the REST adapters' policy. */
  readonly maxRetries?: number;
  /** Test seam: replaces the real timer so retry backoff is instantaneous. */
  readonly sleep?: (ms: number) => Promise<void>;
  /** Number of `getJob` calls before the job reports `completed`. Defaults to 1. */
  readonly pollsBeforeCompletion?: number;
  /**
   * When true the adapter behaves like a keyed provider: an absent credential raises a
   * `CredentialError`, and a vault value of `REJECTED` produces a 401-style failure.
   */
  readonly requireCredentials?: boolean;
  /** Return a malformed catalog body, to exercise the ProviderError path. */
  readonly malformedResponses?: boolean;
  /**
   * Injectable failure hook; receives the call name. Return an Error to fail that call.
   * A returned plain `Error` is typed by `interceptStatus` so the retry policy can reason
   * about it exactly as it would about a real HTTP failure.
   */
  readonly intercept?: (call: string, url: string) => Error | undefined;
  /** HTTP status attributed to an injected plain `Error`. Defaults to 500. */
  readonly interceptStatus?: number;
  /**
   * Override the expiry attached to generated outputs. Contract tests use a past timestamp
   * to prove `fetchOutputs` rejects an expired URL; the default is one hour ahead.
   */
  readonly expiresAt?: string;
}

interface MockJobRecord {
  readonly providerJobId: string;
  readonly request: GenerationRequest;
  readonly outputs: RemoteOutput[];
  readonly cost: Spend | null;
  polls: number;
  status: "running" | "completed" | "canceled";
}

const MOCK_PROVIDER_ID = "mock";
const MOCK_PROVIDER_LABEL = "Mock Provider (deterministic)";

/** Deterministic FNV-1a hash, used for ids, seeds and byte payloads. */
export function fnv1a(input: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

/** The four to six models the mock reports, with fully-populated capability objects. */
export function mockModels(now: () => Date = () => new Date()): ModelDescriptor[] {
  const fetchedAt = now().toISOString();
  const describe = (
    modelId: string,
    displayName: string,
    capabilities: ModelCapabilities,
  ): ModelDescriptor => ({
    providerId: MOCK_PROVIDER_ID,
    modelId,
    displayName,
    modality: capabilities.modality,
    capabilities,
    fetchedAt,
    isStale: false,
  });

  return [
    describe(
      "mock-image-1",
      "Mock Image 1",
      capabilitiesFrom({
        modality: "image",
        modes: ["text-to-image", "image-to-image"],
        inputMimeTypes: ["image/png", "image/jpeg", "image/webp"],
        aspectRatios: ["1:1", "16:9", "9:16"],
        resolutions: ["512x512", "1024x1024", "1024x1792"],
        supportsSeed: true,
        supportsNegativePrompt: true,
        referenceFrame: "optional",
        maxConcurrency: 3,
        pricing: { unit: "per-image", amount: 0.04, currency: "USD" },
        quota: {
          requestsPerMinute: 60,
          requestsPerDay: 1_000,
          maxConcurrentRequests: 3,
          notes: null,
        },
        safety: {
          contentFiltering: true,
          notes: "Deterministic local double; no content leaves the machine.",
        },
      }),
    ),
    describe(
      "mock-video-1",
      "Mock Video 1",
      capabilitiesFrom({
        modality: "video",
        modes: ["text-to-video", "image-to-video"],
        inputMimeTypes: ["image/png", "image/jpeg"],
        aspectRatios: ["16:9", "9:16", "1:1"],
        resolutions: ["720p", "1080p"],
        durationMinSeconds: 2,
        durationMaxSeconds: 10,
        supportsSeed: true,
        supportsNegativePrompt: false,
        referenceFrame: "optional",
        supportsAudio: false,
        maxConcurrency: 2,
        pricing: { unit: "per-second", amount: 0.1, currency: "USD" },
        quota: {
          requestsPerMinute: 10,
          requestsPerDay: 200,
          maxConcurrentRequests: 2,
          notes: null,
        },
        safety: { contentFiltering: true, notes: null },
      }),
    ),
    describe(
      "mock-video-frame-1",
      "Mock Video (first/last frame)",
      capabilitiesFrom({
        modality: "video",
        modes: ["image-to-video", "video-to-video"],
        inputMimeTypes: ["image/png", "video/mp4"],
        aspectRatios: ["16:9", "9:16"],
        resolutions: ["1080p"],
        durationMinSeconds: 4,
        durationMaxSeconds: 8,
        supportsSeed: false,
        supportsNegativePrompt: false,
        referenceFrame: "required",
        supportsAudio: false,
        maxConcurrency: 1,
        pricing: null,
        quota: null,
        safety: { contentFiltering: true, notes: "Requires an explicit first frame." },
      }),
    ),
    describe(
      "mock-speech-1",
      "Mock Speech 1",
      capabilitiesFrom({
        modality: "audio",
        modes: ["tts"],
        inputMimeTypes: ["text/plain"],
        durationMinSeconds: 1,
        durationMaxSeconds: 300,
        supportsSeed: true,
        supportsNegativePrompt: false,
        referenceFrame: "none",
        supportsAudio: true,
        voices: [
          {
            id: "mock-voice-aria",
            name: "Aria",
            languages: ["en-US", "es-ES"],
            gender: "female",
            previewUrl: null,
          },
          {
            id: "mock-voice-atlas",
            name: "Atlas",
            languages: ["en-US", "de-DE"],
            gender: "male",
            previewUrl: null,
          },
        ],
        languages: ["en-US", "es-ES", "de-DE"],
        maxConcurrency: 4,
        pricing: { unit: "per-1k-chars", amount: 0.15, currency: "USD" },
        quota: {
          requestsPerMinute: 120,
          requestsPerDay: null,
          maxConcurrentRequests: 4,
          notes: null,
        },
        safety: { contentFiltering: false, notes: "Consent required for cloned voices (PRD §13)." },
      }),
    ),
    describe(
      "mock-sfx-1",
      "Mock SFX 1",
      capabilitiesFrom({
        modality: "audio",
        modes: ["sfx", "music"],
        inputMimeTypes: ["text/plain"],
        durationMinSeconds: 0.5,
        durationMaxSeconds: 30,
        supportsSeed: true,
        supportsNegativePrompt: true,
        referenceFrame: "none",
        supportsAudio: true,
        languages: [],
        maxConcurrency: 2,
        pricing: { unit: "per-request", amount: 0.02, currency: "USD" },
        quota: null,
        safety: { contentFiltering: false, notes: null },
      }),
    ),
    describe(
      "mock-transcribe-1",
      "Mock Transcribe 1",
      capabilitiesFrom({
        modality: "text",
        modes: ["transcription"],
        inputMimeTypes: ["audio/wav", "audio/mpeg", "video/mp4"],
        supportsSeed: false,
        supportsNegativePrompt: false,
        referenceFrame: "required",
        supportsAudio: true,
        languages: ["en-US", "es-ES"],
        maxConcurrency: 2,
        pricing: { unit: "per-second", amount: 0.0004, currency: "USD" },
        quota: null,
        safety: { contentFiltering: false, notes: null },
      }),
    ),
  ];
}

export class MockAdapter implements ProviderAdapter {
  readonly id = MOCK_PROVIDER_ID;
  readonly displayName = MOCK_PROVIDER_LABEL;

  private readonly options: MockAdapterOptions;
  private readonly now: () => Date;
  private readonly maxRetries: number;
  private readonly sleep: (ms: number) => Promise<void>;
  private listAttempts = 0;
  private readonly models: ModelDescriptor[];
  private readonly jobs = new Map<string, MockJobRecord>();
  private readonly submissions = new Map<string, MockJobRecord>();
  private submitAttempts = 0;

  constructor(options: MockAdapterOptions = {}) {
    this.options = options;
    this.now = options.now ?? (() => new Date());
    this.maxRetries = Math.max(0, options.maxRetries ?? 2);
    this.sleep =
      options.sleep ?? ((ms: number) => new Promise((resolve) => setTimeout(resolve, ms)));
    this.models = mockModels(this.now);
  }

  get providerJobIdPrefix(): string {
    return `${this.id}-job`;
  }

  // -------------------------------------------------------------------------
  // Catalog
  // -------------------------------------------------------------------------

  async listModels(ctx: ProviderContext): Promise<ModelDescriptor[]> {
    // Mirrors `HttpClient`: a retryable failure is retried with exponential backoff +
    // jitter (`nextBackoffDelay`) up to `maxRetries`, so the double exercises the same
    // retry policy the REST adapters use.
    let attempt = 0;
    for (;;) {
      await this.delay();
      this.listAttempts += 1;
      try {
        return await this.listModelsOnce(ctx);
      } catch (error) {
        const normalized = this.normalizeError(error);
        if (!normalized.retryable || attempt >= this.maxRetries) throw normalized;
        const delayMs = nextBackoffDelay({
          attempt,
          baseMs: 250,
          capMs: 30_000,
          retryAfterSeconds: normalized.retryAfterSeconds,
          random: () => 0,
          jitter: "equal",
        });
        await this.sleep(delayMs);
        attempt += 1;
      }
    }
  }

  private async listModelsOnce(ctx: ProviderContext): Promise<ModelDescriptor[]> {
    this.throwIfIntercepted("listModels", "mock://models");
    if (this.options.malformedResponses) {
      throw new ProviderError(
        "Provider returned a malformed JSON body for GET mock://models (status 200).",
        {
          category: "provider",
          status: 200,
          details: { url: "mock://models", excerpt: "<html>not json</html>" },
        },
      );
    }
    await this.assertCredentials(ctx);
    return this.models.map((descriptor) => ({
      ...descriptor,
      capabilities: { ...descriptor.capabilities },
    }));
  }

  async describeCapabilities(modelId: string): Promise<ModelCapabilities> {
    const model = this.models.find((descriptor) => descriptor.modelId === modelId);
    if (!model) {
      throw new ProviderError(`Mock adapter has no model "${modelId}".`, {
        category: "validation",
        status: 404,
      });
    }
    return model.capabilities;
  }

  async estimateCost(request: GenerationRequest): Promise<Spend | null> {
    const model = this.models.find((descriptor) => descriptor.modelId === request.modelId);
    const pricing = model?.capabilities.pricing ?? null;
    if (!pricing) return null;
    return costFromPricing(pricing, billableUnits(request, model?.capabilities ?? null));
  }

  validate(request: GenerationRequest, capabilities: ModelCapabilities): ValidationResult {
    return validateRequest(request, capabilities);
  }

  // -------------------------------------------------------------------------
  // Jobs
  // -------------------------------------------------------------------------

  async submit(request: GenerationRequest, ctx: ProviderContext): Promise<SubmitResult> {
    await this.delay();
    await this.assertCredentials(ctx);
    this.throwIfIntercepted("submit", "mock://generate");

    this.submitAttempts += 1;
    const failFirstN = this.options.failFirstN ?? 0;
    if (this.submitAttempts <= failFirstN) throw this.injectedFailure();

    const jobKey = `${request.providerId}:${request.modelId}:${request.mode}:${request.prompt}:${request.seed ?? ""}`;
    const existing = this.submissions.get(jobKey);
    if (existing && existing.status === "running") {
      // Idempotent submission: the same request returns the same provider job.
      return {
        providerJobId: existing.providerJobId,
        status: "running",
        submittedAt: this.now().toISOString(),
      };
    }

    const providerJobId = `${this.providerJobIdPrefix}-${fnv1a(jobKey).toString(16)}`;
    const capabilities = this.models.find(
      (descriptor) => descriptor.modelId === request.modelId,
    )?.capabilities;
    const outputs = this.buildOutputs(
      request,
      providerJobId,
      capabilities,
      this.options.expiresAt ?? null,
    );
    const record: MockJobRecord = {
      providerJobId,
      request,
      outputs,
      cost: await this.estimateCost(request),
      polls: 0,
      status: "running",
    };
    this.jobs.set(providerJobId, record);
    this.submissions.set(jobKey, record);
    if (this.completesImmediately()) {
      record.status = "completed";
      return { providerJobId, status: "completed", outputs, submittedAt: this.now().toISOString() };
    }
    return { providerJobId, status: "running", submittedAt: this.now().toISOString() };
  }

  async getJob(jobId: string, ctx: ProviderContext): Promise<JobStatusResult> {
    await this.delay();
    await this.assertCredentials(ctx);
    this.throwIfIntercepted("getJob", `mock://jobs/${jobId}`);
    const record = this.jobs.get(jobId);
    if (!record) {
      throw new ProviderError(`Mock adapter has no job "${jobId}".`, {
        category: "validation",
        status: 404,
      });
    }
    if (record.status === "canceled") return { status: "canceled", progress: null };
    const needed = Math.max(1, this.options.pollsBeforeCompletion ?? 1);
    record.polls += 1;
    const done = this.completesImmediately() || record.polls >= needed;
    if (done) {
      record.status = "completed";
      return {
        status: "completed",
        progress: 1,
        outputs: record.outputs,
        cost: record.cost,
      };
    }
    return {
      status: "running",
      progress: Math.min(0.95, record.polls / needed),
      retryAfterSeconds: 0.01,
    };
  }

  async cancel(jobId: string, ctx: ProviderContext): Promise<void> {
    await this.delay();
    await this.assertCredentials(ctx);
    this.throwIfIntercepted("cancel", `mock://jobs/${jobId}`);
    const record = this.jobs.get(jobId);
    if (record) record.status = "canceled";
  }

  /**
   * Materialize the output bytes.
   *
   * Expiry is enforced first: an output URL that has already expired is rejected, exactly
   * as a real signed URL would be.
   */
  async fetchOutputs(job: JobStatusResult, ctx: ProviderContext): Promise<RemoteOutput[]> {
    await this.delay();
    await this.assertCredentials(ctx);
    this.throwIfIntercepted("fetchOutputs", "mock://outputs");
    const outputs = job.outputs ?? [];
    assertOutputsFresh(outputs, this.now());
    for (const output of outputs) {
      // Validate the payload can actually be produced; a broken URL is a provider error.
      this.bytesFor(output);
    }
    return outputs;
  }

  /**
   * Deterministic bytes addressed by the output URL. `MockBytesFetcher` (and any consumer
   * that needs the raw payload) calls this rather than re-deriving the scheme.
   */
  bytesFor(output: RemoteOutput): Uint8Array {
    const seed = fnv1a(output.url) + (this.options.seedOutputs ?? 0);
    switch (output.kind) {
      case "image":
        return encodePng({
          width: 64,
          height: 64,
          rgb: [40 + (seed % 64), 90, 180],
          gradient: seed % 16,
        });
      case "video":
        return encodeVideoBlob(seed, 4_096);
      case "audio": {
        const wav = encodeWav({
          sampleRate: 44_100,
          channels: 1,
          bitsPerSample: 16,
          durationSeconds: 1,
          silent: true,
          seed,
        });
        return wav.bytes;
      }
      case "text":
        return encodeText(
          `[mock transcript ${seed.toString(16)}] Deterministic transcription payload.\n`,
        );
      default: {
        const exhaustive: never = output.kind;
        throw new ProviderError(`Unsupported mock output kind ${String(exhaustive)}.`, {
          category: "internal",
        });
      }
    }
  }

  normalizeError(error: unknown): CreativeLabError {
    return normalizeProviderError(error);
  }

  // -------------------------------------------------------------------------
  // Internals
  // -------------------------------------------------------------------------

  private buildOutputs(
    request: GenerationRequest,
    providerJobId: string,
    capabilities: ModelCapabilities | undefined,
    expiresAtOverride: string | null,
  ): RemoteOutput[] {
    const modality = capabilities?.modality ?? "image";
    const expiresAt =
      expiresAtOverride ?? new Date(this.now().getTime() + 60 * 60_000).toISOString();
    const base = `mock://outputs/${providerJobId}/${fnv1a(JSON.stringify({ p: request.prompt, s: request.seed ?? null }))}`;
    if (modality === "video") {
      return [
        { url: `${base}.mp4`, mimeType: "video/mp4", kind: "video", bytes: 4_096, expiresAt },
      ];
    }
    if (modality === "audio") {
      const wav = encodeWav({ durationSeconds: 1 });
      return [
        {
          url: `${base}.wav`,
          mimeType: "audio/wav",
          kind: "audio",
          bytes: wav.bytes.length,
          expiresAt,
        },
      ];
    }
    if (modality === "text" || modality === "subtitle") {
      return [{ url: `${base}.txt`, mimeType: "text/plain", kind: "text", expiresAt }];
    }
    const png = encodePng({ width: 64, height: 64 });
    return [
      { url: `${base}.png`, mimeType: "image/png", kind: "image", bytes: png.length, expiresAt },
    ];
  }

  private completesImmediately(): boolean {
    return (this.options.latencyMs ?? 0) === 0 && (this.options.pollsBeforeCompletion ?? 1) <= 0;
  }

  private injectedFailure(): Error {
    const config = this.options.failWith ?? {};
    const status = config.status ?? 500;
    const message = config.message ?? `Mock provider rejected the submission (status ${status}).`;
    if (config.category || config.retryable !== undefined || config.uncertain !== undefined) {
      return new ProviderError(message, {
        category: config.category ?? "provider",
        retryable: config.retryable ?? (status >= 500 || status === 429),
        status,
        uncertain: config.uncertain,
      });
    }
    return submissionError(
      {
        ok: false,
        status,
        statusText: status === 429 ? "Too Many Requests" : status >= 500 ? "Server Error" : "Error",
      },
      { url: "mock://generate", method: "POST", body: { error: message } },
    );
  }

  private throwIfIntercepted(call: string, url: string): void {
    const injected = this.options.intercept?.(call, url);
    if (!injected) return;
    if (injected instanceof ProviderError || injected instanceof CredentialError) throw injected;
    // Normalize like the REST adapters do, so an injected plain `Error` still surfaces as a
    // `CreativeLabError` the retry policy can reason about (status/retryable included).
    const status = this.options.interceptStatus ?? 500;
    throw new ProviderError(injected.message, {
      category: classifyHttpStatus(status).category ?? "provider",
      retryable: classifyHttpStatus(status).retryable ?? false,
      status,
      details: { call, url, providerId: this.id },
      cause: injected,
    });
  }

  private async assertCredentials(ctx: ProviderContext): Promise<void> {
    if (!this.options.requireCredentials) return;
    const ref = "provider:mock";
    const secret = await ctx.credentials.get(ref);
    if (!secret) {
      throw new ProviderError("No credential is configured for the mock provider.", {
        category: "credential",
        status: 401,
        details: { ref },
      });
    }
    if (secret === "REJECTED") {
      throw credentialErrorFromResponse(
        { ok: false, status: 401, statusText: "Unauthorized" },
        { url: "mock://models" },
      );
    }
  }

  private async delay(): Promise<void> {
    const latencyMs = this.options.latencyMs ?? 0;
    if (latencyMs > 0) await new Promise((resolve) => setTimeout(resolve, latencyMs));
  }

  /** Test seam: how many submissions were attempted (including injected failures). */
  submissionAttempts(): number {
    return this.submitAttempts;
  }

  /** Test seam: reset failure injection counters. */
  reset(): void {
    this.submitAttempts = 0;
    this.listAttempts = 0;
    this.jobs.clear();
    this.submissions.clear();
  }

  /** Every issue a request would produce, for tests that assert field names directly. */
  static issuesFor(result: ValidationResult): Issue[] {
    return [...result.errors, ...result.unsupported];
  }
}

export { MOCK_PROVIDER_ID, MOCK_PROVIDER_LABEL };
